### ISSUE TITLE
Invalid configuration

### ISSUE THREAD

**Issue by paddockDev** [TomasVotruba/bladestan#34]
Based on the fact that I already use Larastan in my projects, I wanted to try bladestan in addition. Unfortunately, however, I make the experience, no matter how I configure phpstan.neon, I am always told invalid configuration. 

```
Invalid configuration:
Unexpected item 'parameters › bladestan'.
```

I tried it together with larastan configuration, but also just took out that configuration and wanted to run the bladestan configuration alone.

**Comment by TomasVotruba** [comment]
Could you share minimal reproducer?
I suspect missing phpstan extension-installler

**Comment by paddockDev** [comment]
For example, my larastan configuration looks like this
```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    paths:
        - app

    level: 8

    ignoreErrors:

    checkMissingIterableValueType: false

    checkModelProperties: true

    checkGenericClassInNonGenericObjectType: false
``` 

According to my understanding, if I want to run both bladestan and larastan through phpstan.neon, then the configuartion should look like this.

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    bladestan:
        template_paths:
            # default
            - resources/views

    paths:
        - app

    level: 8

    ignoreErrors:

    checkMissingIterableValueType: false

    checkModelProperties: true

    checkGenericClassInNonGenericObjectType: false
```

But even with your example of configuration alone I get the above error
